root: ./

redirects:
  developing/overview: README.md
  developing/0_introduction: developing/0_introduction.md
  developing/1_get_started: developing/1_get-started.md
  developing/2_architecture: developing/2_architecture.md
  developing/3_configuration: developing/3_configuration.md
  developing/4_inputs: developing/4_inputs.md
  developing/5_llms: developing/5_llms.md
  developing/6_actions: developing/6_actions.md
  developing/7_project_structure: developing/7_project_structure.md
  developing/8_backgrounds: developing/8_backgrounds.md
  developing/9_troubleshooting_guide: developing/9_troubleshooting_guide.md
  api-reference/introduction: api-reference/introduction.md
  api-reference/api_pricing: api-reference/api_pricing.md
  api-reference/endpoints/google-asr: api-reference/endpoints/google_asr.md
  api-reference/endpoints/account-and-key-management: api-reference/endpoints/account_and_key_management.md
  api-reference/endpoints/elevenlabs-tts: api-reference/endpoints/elevenlabs_tts.md
  api-reference/endpoints/llm: api-reference/endpoints/llm.md
  api-reference/endpoints/riva: api-reference/endpoints/riva.md
  api-reference/endpoints/vila-vlm: api-reference/endpoints/vila_vlm.md
  developer-cookbook/introduction: developer_cookbook/introduction.md
  developer-cookbook/config: developer_cookbook/config.md
  developer-cookbook/input: developer_cookbook/input.md
  developer-cookbook/new-mode: developer_cookbook/new_mode.md
  examples/overview: examples/overview.md
  examples/conversation: examples/conversation.md
  examples/gazebo: examples/gazebo.md
  examples/llm-models: examples/llm_models.md
  examples/smart-toy: examples/smart_toy.md
  full-autonomy-guidelines/brainpack-introduction: full_autonomy_guidelines/brainpack_introduction.md
  full-autonomy-guidelines/architecture-overview: full_autonomy_guidelines/architecture_overview.md
  full-autonomy-guidelines/setup-system: full_autonomy_guidelines/setup_system.md
  full-autonomy-guidelines/system-config: full_autonomy_guidelines/system_config.md
  full-autonomy-guidelines/modes: full_autonomy_guidelines/modes.md
  full-autonomy-guidelines/mode-selection: full_autonomy_guidelines/mode_selection.md
  full-autonomy-guidelines/transition-rules: full_autonomy_guidelines/transition_rules.md
  full-autonomy-guidelines/lifecycle: full_autonomy_guidelines/lifecycle.md
  full-autonomy-guidelines/ota-setup: full_autonomy_guidelines/ota_setup.md
  robotics/asimov-governance: robotics/asimov_governance.md
  robotics/coinbase-hackathon: robotics/coinbase_hackathon.md
  robotics/coinbase-x402: robotics/coinbase-x402.md
  robotics/crsf-long-range-control: robotics/crsf_long_range_control.md
  robotics/gps-compass: robotics/gps_compass.md
  robotics/motion-planning-lidarA1M8: robotics/motion_planning_lidarA1M8.md
  robotics/motion-planning-turtlebot4: robotics/motion_planning_turtlebot4.md
  robotics/motion-planning-unitree-go2: robotics/motion_planning_unitree_go2.md
  robotics/rf-mapping: robotics/rf_mapping.md
  robotics/tesla-dimo: robotics/tesla_dimo.md
  robotics/turtlebot4-zenoh: robotics/turtlebot4_zenoh.md
  robotics/ubtech-yanshee: robotics/ubtech_yanshee.md
  robotics/unitree-g1-humanoid: robotics/unitree_g1_humanoid.md
  robotics/unitree-go2-quadruped-configurations: robotics/unitree_go2_quadruped_configurations.md
  robotics/unitree-go2-quadruped: robotics/unitree_go2_quadruped.md
  robotics/mac: robotics/mac.md
  robotics/media-server: robotics/Media_server.md
  robotics/nvidia-thor: robotics/nvidia_thor.md
  robotics/raspberrypi: robotics/raspberrypi.md
  robotics/zenoh: robotics/zenoh.md
  release-notes/beta/om: release-notes/beta/om.md
  release-notes/beta/om1-avatar: release-notes/beta/om1-avatar.md
  release-notes/beta/om1-ros2-sdk: release-notes/beta/om1-ros2-sdk.md
  release-notes/beta/video-processor: release-notes/beta/video-processor.md
  release-notes/major-updates/beta-release: release-notes/major-updates/beta_release.md
  release-notes/major-updates/production-ready-release: release-notes/major-updates/production_ready_release.md
  release-notes/v1.0.0/om: release-notes/v1.0.0/om.md
  release-notes/v1.0.0/om1-avatar: release-notes/v1.0.0/om1-avatar.md
  release-notes/v1.0.0/om1-ros2-sdk: release-notes/v1.0.0/om1-ros2-sdk.md
  release-notes/v1.0.0/om1-system-setup: release-notes/v1.0.0/om1-system-setup.md
  release-notes/v1.0.0/video-processor: release-notes/v1.0.0/video-processor.md
